### PR TITLE
Quote dir arguments to setup and compile.

### LINKED ISSUE #203: Path issue when using cygwin as vscode integrated console on Windows
I'm using cygwin as vscode integrated console, but I found when I update this extension to version 1.8.1, it can't reconfigure my project any more, then I back to version 1.8.0. and that version has no problem.

v1.8.1:
image

v1.8.0:
image

### PR DESCRIPTION
**Pull request by lukester1975**
Hopefully fixes #203.

### CODE REVIEW

**Comment by tristan957** [comment]
@ZZH-Finzlize can you confirm if this work or not

**Comment by xclaesse** [comment]
I guess this is the problem when using ShellExecution, it opens the quoting can of worms. I imagine `vscode.ProcessExecution()` does not have that problem.

**Comment by xclaesse** [comment]
Is there a downside in using `vscode.ProcessExecution()` everywhere? If quoting is needed, we could have the same issue from meson options that could contain path with spaces (`-Dprefix=/foo with spaces/bar`).

**Comment by ZZH-Finzlize** [comment]
@tristan957 I don't know how to test this PR, it seems need to manually replace the extension program and I don't know how to do that. Is there any document or something like that?

**Comment by ZZH-Finzlize** [comment]
> @tristan957 I don't know how to test this PR, it seems need to manually replace the extension program and I don't know how to do that. Is there any document or something like that?

I think I figured it out. I tested this PR, and It does solved #203.

Test result:
image

@tristan957 @lukester1975  Thanks for everyone who helped with my issue.

**Comment by tristan957** [comment]
@lukester1975 thanks for your help with the extension so far. Decided to go with the other solution, but appreciate your effort nevertheless.

**Pull request closed without merging**
