### PR TITLE
Fix "s.sources" is not iterable

### PR DESCRIPTION
**Pull request by tristan957**
When exploring the project tree, I ran into this error.

### CODE REVIEW

**Comment by tristan957** [comment]
@xclaesse you mind taking a look at the type changes?

**Comment by xclaesse** [comment]
Sure, LGTM

**Comment by tristan957** [comment]
But does this match what Meson outputs in introspection?

**Comment by xclaesse** [comment]
I think in theory the introspection json should have empty list `"generated_sources" : []`, but I assume since you're doing this PR you found a case it's null?

**Comment by tristan957** [comment]
I only saw the issue with `sources`. I was just being safe with the `generated_sources`.

**Pull request merged**
