### PR TITLE
add setupOptions configuration, useful for passing --cross-file to meson setup

### PR DESCRIPTION
**Pull request by chris-laplante**
Partial fix for #46

### CODE REVIEW

**Comment by Ongy** [comment]
Can we call this `configOptions` or `configureOptions` or similar?

Then it matches the actual command.

**Comment by chris-laplante** [comment]
> Can we call this `configOptions` or `configureOptions` or similar?
> 
> Then it matches the actual command.

`meson setup` _is_ a command that is used by this plugin. Plus there's already a `mesonbuild.configureOptions` which corresponds to `meson configure` (though it's also passed to `meson setup` for some reason).

**Comment by Ongy** [comment]
I'm dumb, sorry. LGTM

**Review by Ongy — APPROVED** [review]

**Comment by chris-laplante** [comment]
> I'm dumb, sorry. LGTM

No problem, thanks for merging :)

**Pull request merged**
